apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-quarkus
  namespace: mkovarik
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: registry
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-quarkus-
      labels:
        build.appstudio.openshift.io/application: registry
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: mkovarik
    spec:
      params:
      - name: git-url
        value: https://github.com/Michkov/apicurio-registry
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:mkovarik-java-quarkus-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/mkovarik/hacbs-templates-bundle:latest
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-quarkus/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
